### ISSUE TITLE
Active alert ribbon widgets cover the search box

### ISSUE THREAD

**Issue by ryanlebreton-gmu** [jmacario-gmu/gmuj-mason-wordpress-theme-twentytwenty-child#14]
![Annotation 2021-02-19 142737](https://user-images.githubusercontent.com/54120260/108551957-a7d46780-72be-11eb-9bee-c21eaf968e43.jpg)

**Comment by jmacario-gmu** [comment]
This was fixed via a modification to the custom alerts widget. Thanks for raising the issue and for the fix!
