### ISSUE TITLE
Highlight item widget overlaps main menu

### ISSUE THREAD

**Issue by ryanlebreton-gmu** [jmacario-gmu/gmuj-mason-wordpress-theme-twentytwenty-child#15]
![highlight_overlap](https://user-images.githubusercontent.com/54120260/108553602-ebc86c00-72c0-11eb-8ba6-9c1622a9a165.png)

**Comment by jmacario-gmu** [comment]
Thanks for looking into this.
However it looks like this issue was obviated by changes to the theme.
I'm marking this issue closed.
